spring:
  application:
    name: book-reader
  profiles:
    active: jdbc

server:
  servlet:
    context-path: /book-reader


logging:
  level:
    com.graduation.bookreader.repo : debug
#  config: classpath:log4j.xml # 指定log4j配置文件的位置
